# Generated by Django 5.1.3 on 2025-02-24 01:28

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('admin_side', 'Category')
    
    categories = [
        ('Fiction', 'fiction'),
        ('Non-Fiction', 'non-fiction'),
        ('Science Fiction', 'sci-fi'),
        ('Comics', 'comics'),
        ('Self-Help', 'self-help')
    ]
    
    for name, slug in categories:
        Category.objects.create(
            name=name,
            slug=slug,
            description=f'Collection of {name.lower()} books'
        )


def reverse_migration(apps, schema_editor):
    Category = apps.get_model('admin_side', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_migration),
    ]
