# Generated by Django 5.0.2 on 2025-03-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_remove_coupon_is_used_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralhistory',
            name='reward_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
