# Generated by Django 5.1.7 on 2025-03-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0010_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoffer',
            options={'ordering': ['-discount_percentage'], 'verbose_name_plural': 'Category Offers'},
        ),
        migrations.AlterModelOptions(
            name='productoffer',
            options={'ordering': ['-discount_percentage'], 'verbose_name_plural': 'Product Offers'},
        ),
    ]
