# Generated by Django 5.1.7 on 2025-03-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0011_alter_categoryoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productoffer',
            options={'ordering': ['-created_at']},
        ),
    ]
