# Generated by Django 5.1.7 on 2025-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0012_alter_categoryoffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_admin_generated',
            field=models.BooleanField(default=False, help_text='Indicates if this coupon was generated by an admin for a specific user'),
        ),
    ]
