# Generated by Django 6.0 on 2026-01-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0016_populate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
