# Generated by Django 6.0 on 2026-01-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0017_product_isbn_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
