# Generated by Django 6.0 on 2026-01-10 03:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0019_product_category_schema_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('malayalam', 'Malayalam')], default='english', max_length=20),
        ),
    ]
