# Generated by Django 5.1.3 on 2025-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_section', '0001_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('RETURN_REQUESTED', 'Return Requested')], default='PENDING', max_length=20),
        ),
    ]
