# Generated by Django 5.0.2 on 2025-03-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_section', '0002_add_orderitem_status'),
        ('cart_section', '0004_alter_order_status'),
    ]

    operations = [
    ]
