# Generated by Django 5.1.6 on 2025-02-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_otpverification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
