# Generated by Django 5.1.3 on 2025-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_accountdetails_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='email_otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
